# Generated by Django 4.0.2 on 2022-02-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_produto_categoria_produto_marca_produto_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fabricante',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sub_categoria',
            field=models.TextField(null=True),
        ),
    ]
