# Generated by Django 4.0.2 on 2022-02-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
