# Generated by Django 4.0.2 on 2022-02-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
